### ISSUE TITLE
创建tag和category页面时报错

### ISSUE THREAD

**Issue by ZhenyuanMA** [Siricee/hexo-theme-Chic#51]
您好，根据您的文档，我用hexo new page增加了tag和category， 并在md文档中添加了label。但在hexo generate命令后有报错。报错信息如下：
```
ERROR Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/category.ejs"
SyntaxError: Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/category.ejs"
    at new Function (<anonymous>)
    at exports.compile (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:242:14)
    at Object.exports.render (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:284:66)
    at Hexo.<anonymous> (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/index.js:14:24)
    at Hexo.tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/Users/leef/.nvm/versions/node/v10.9.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/Users/leef/Desktop/fisher/homepage/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
ERROR Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/tag.ejs"
SyntaxError: Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/tag.ejs"
    at new Function (<anonymous>)
    at exports.compile (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:242:14)
    at Object.exports.render (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:284:66)
    at Hexo.<anonymous> (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/index.js:14:24)
    at Hexo.tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/Users/leef/.nvm/versions/node/v10.9.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/Users/leef/Desktop/fisher/homepage/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
ERROR Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/tag.ejs"
SyntaxError: Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/tag.ejs"
    at new Function (<anonymous>)
    at exports.compile (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:242:14)
    at Object.exports.render (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:284:66)
    at Hexo.<anonymous> (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/index.js:14:24)
    at Hexo.tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/Users/leef/.nvm/versions/node/v10.9.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/Users/leef/Desktop/fisher/homepage/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
ERROR Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/tag.ejs"
SyntaxError: Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/tag.ejs"
    at new Function (<anonymous>)
    at exports.compile (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:242:14)
    at Object.exports.render (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:284:66)
    at Hexo.<anonymous> (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/index.js:14:24)
    at Hexo.tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/Users/leef/.nvm/versions/node/v10.9.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/Users/leef/Desktop/fisher/homepage/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```
在server中尝试点开某个tag也会报错，错误如下：
```
Unhandled rejection SyntaxError: Invalid or unexpected token in "/Users/leef/Desktop/fisher/homepage/themes/Chic/layout/tag.ejs"
    at new Function (<anonymous>)
    at exports.compile (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:242:14)
    at Object.exports.render (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:289:10)
    at Hexo.<anonymous> (/Users/leef/Desktop/fisher/homepage/node_modules/hexo-renderer-mathjax/index.js:14:24)
    at Hexo.tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/Users/leef/.nvm/versions/node/v10.9.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/Users/leef/Desktop/fisher/homepage/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/leef/Desktop/fisher/homepage/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```
想请问是什么原因呢？谢谢！

**Comment by Siricee** [comment]
`SyntaxError: Invalid or unexpected token`，你可能是用了什么英文字符或多打了什么字符。重新安装一下主题和这两个页面试试

**Comment by ZhenyuanMA** [comment]
您好，重新安装仍然是这个报错，请问可能会是什么英文字符的问题呢？

**Comment by Siricee** [comment]
两个页面的frontMatter可能有问题，你复制粘贴我的文档示例试下。另外重装主题请执行下`hexo clean` 你说的这个问题也可能是缓存有问题，我也遇到过，后来莫名其妙的就好了。。。

**Comment by ZhenyuanMA** [comment]
是复制粘贴了您的示例，并且也执行了hexo clean。我再尝试寻找一下问题吧

**Comment by ZhenyuanMA** [comment]
现在已经解决了在`hexo generate`时的报错，原因是文章的其中一个tag里面带有空格。
tag以及category页面在public文件夹中正常生成，直接打开index.html也可以显示，但在`hexo server`中点击tag以及vategory相关仍会报错。

**Comment by Siricee** [comment]
给你个 FrontMatter 格式参考吧
```markdown
---
title: 从零开始创建一个hexo主题
date: 2019-06-02 14:19:49 # 注意yaml语法，冒号后面有空格
tags: [hexo,Chic,FrontEnd]  # 数组以方括号形式声明
category: how to build a hexo theme
---
```

**Comment by ZhenyuanMA** [comment]
感谢您的回复。
经过不断测试发现，偶尔会有`hexo generate`不报错的情况，点击tag仍然报错。但再次clean之后可能又报错了，无法生成页面。（sad
现在已经关掉了tag和category页面，只能以后随缘了。
再次感谢您的帮助。
